# Generated by Django 4.2.1 on 2023-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_user_is_verified_email_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_add',
            field=models.FileField(blank=True, null=True, upload_to='add_files'),
        ),
    ]
